// Copyright 2019 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

package parser

import (
	"bytes"
	"crypto/sha256"
	hash2 "hash"
	"sync"
)

type Digest struct {
	b   []byte
	str string
}

// NewDigest returns a new digest.
func NewDigest(b []byte) *Digest { _ = "STUB: not implemented"; return nil }

// String returns the digest hex string.
func (d *Digest) String() string {
	_ = "STUB: not implemented"

	// Bytes returns the digest byte slice.
	return ""
}

func (d *Digest) Bytes() []byte {
	_ = "STUB: not implemented"

	// DigestHash generates the digest of statements.
	// it will generate a hash on normalized form of statement text
	// which removes general property of a statement but keeps specific property.
	//
	// for example: both DigestHash('select 1') and DigestHash('select 2') => e1c71d1661ae46e09b7aaec1c390957f0d6260410df4e4bc71b9c8d681021471
	//
	// Deprecated: It is logically consistent with NormalizeDigest.
	return nil
}

func DigestHash(sql string) (digest *Digest) { _ = "STUB: not implemented"; return nil }

// DigestNormalized generates the digest of a normalized sql.
// it will generate a hash on a normalized sql.
// Normalize + DigestNormalized equals to NormalizeDigest.
//
// for example: DigestNormalized('select ?')
// DigestNormalized should be called with a normalized SQL string (like 'select ?') generated by function Normalize.
// do not call with SQL which is not normalized, DigestNormalized('select 1') and DigestNormalized('select 2') is not the same
func DigestNormalized(normalized string) (digest *Digest) { _ = "STUB: not implemented"; return nil }

// Normalize generates the normalized statements.
// it will get normalized form of statement text
// which removes general property of a statement but keeps specific property.
//
// for example: Normalize('select 1 from b where a = 1') => 'select ? from b where a = ?'
func Normalize(sql string) (result string) { _ = "STUB: not implemented"; return "" }

// NormalizeDigest combines Normalize and DigestNormalized into one method.
func NormalizeDigest(sql string) (normalized string, digest *Digest) {
	_ = "STUB: not implemented"
	return "", nil
}

var digesterPool = sync.Pool{
	New: func() interface{} {
		return &sqlDigester{
			lexer:  NewScanner(""),
			hasher: sha256.New(),
		}
	},
}

// sqlDigester is used to compute DigestHash or Normalize for sql.
type sqlDigester struct {
	buffer bytes.Buffer
	lexer  *Scanner
	hasher hash2.Hash
	tokens tokenDeque
}

func (d *sqlDigester) doDigestNormalized(normalized string) (digest *Digest) {
	_ = "STUB: not implemented"
	return nil
}

func (d *sqlDigester) doDigest(sql string) (digest *Digest) { _ = "STUB: not implemented"; return nil }

func (d *sqlDigester) doNormalize(sql string) (result string) { _ = "STUB: not implemented"; return "" }

func (d *sqlDigester) doNormalizeDigest(sql string) (normalized string, digest *Digest) {
	_ = "STUB: not implemented"
	return "", nil
}

const (
	// genericSymbol presents parameter holder ("?") in statement
	// it can be any value as long as it is not repeated with other tokens.
	genericSymbol = -1
	// genericSymbolList presents parameter holder lists ("?, ?, ...") in statement
	// it can be any value as long as it is not repeated with other tokens.
	genericSymbolList = -2
)

func (d *sqlDigester) normalize(sql string) { _ = "STUB: not implemented"; return }

func (d *sqlDigester) reduceOptimizerHint(tok *token) (reduced bool) {
	_ = "STUB: not implemented"
	// ignore /*+..*/
	return false
}

// ignore force/use/ignore index(x)

// ignore straight_join

func (d *sqlDigester) reduceLit(currTok *token) { _ = "STUB: not implemented"; return }

// count(*) => count(?)

// "-x" or "+x" => "x"

// "?, ?, ?, ?" => "..."

// order by n => order by n

// 2 => ?

func (d *sqlDigester) isPrefixByUnary(currTok int) (isUnary bool) {
	_ = "STUB: not implemented"
	return false
}

// a[0] != '-' and a[0] != '+'

// '(-x' or ',-x' or ',+x' or '--x' or '+-x'

// select -x or select +x

func (d *sqlDigester) isGenericList(last2 []token) (generic bool) {
	_ = "STUB: not implemented"
	return false
}

func (d *sqlDigester) isOrderOrGroupBy() (orderOrGroupBy bool) {
	_ = "STUB: not implemented"
	return false
}

// skip number item lists, e.g. "order by 1, 2, 3" should NOT convert to "order by ?, ?, ?"

// handle group by number item list surround by "()", e.g. "group by (1, 2)" should not convert to "group by (?, ?)"

func (d *sqlDigester) isStarParam() (starParam bool) { _ = "STUB: not implemented"; return false }

func (d *sqlDigester) isLit(t token) (beLit bool) { _ = "STUB: not implemented"; return false }

func (d *sqlDigester) isNumLit(tok int) (beNum bool) { _ = "STUB: not implemented"; return false }

func (d *sqlDigester) isComma(tok token) (isComma bool) { _ = "STUB: not implemented"; return false }

type token struct {
	tok int
	lit string
}

type tokenDeque []token

func (s *tokenDeque) reset() { _ = "STUB: not implemented"; return }

func (s *tokenDeque) pushBack(t token) { _ = "STUB: not implemented"; return }

func (s *tokenDeque) popBack(n int) (t []token) { _ = "STUB: not implemented"; return nil }

func (s *tokenDeque) back(n int) (t []token) { _ = "STUB: not implemented"; return nil }
